# SPDX-License-Identifier: BSD-3-Clause
set(directory "${WORK_DIRECTORY}/executable-é")
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  set(minimum_length 1100)
elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
  set(minimum_length 600)
else()
  # Long Windows paths need a host policy/manifest; Unicode is unconditional.
  set(minimum_length 140)
endif()
string(LENGTH "${directory}" length)
while(length LESS minimum_length)
  string(APPEND directory "/segment_0123456789012345678901234567890123456789")
  string(LENGTH "${directory}" length)
endwhile()
file(MAKE_DIRECTORY "${directory}")
file(COPY "${PROBE_EXECUTABLE}" DESTINATION "${directory}")
get_filename_component(name "${PROBE_EXECUTABLE}" NAME)
# Only the executable moves; Windows must still find Core beside the original probe.
if(CMAKE_HOST_WIN32)
  get_filename_component(runtime_directory "${PROBE_EXECUTABLE}" DIRECTORY)
  set(ENV{PATH} "${runtime_directory};$ENV{PATH}")
endif()
execute_process(COMMAND "${directory}/${name}" "${directory}" RESULT_VARIABLE result)
file(REMOVE_RECURSE "${WORK_DIRECTORY}/executable-é")
if(NOT result STREQUAL "0")
  message(FATAL_ERROR "Executable path probe failed: ${result}")
endif()
