# SPDX-License-Identifier: BSD-3-Clause
# Source archives supply assertions; Git checkouts always use the observed state.
function(openms_source_identity source revision dirty)
  if(EXISTS "${source}/.git")
    find_package(Git REQUIRED)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
      WORKING_DIRECTORY "${source}" OUTPUT_VARIABLE _revision
      OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "Cannot determine Core source revision")
    endif()
    if(OPENMS_SOURCE_REVISION AND NOT OPENMS_SOURCE_REVISION STREQUAL _revision)
      message(FATAL_ERROR "OPENMS_SOURCE_REVISION disagrees with the Core checkout; clear the override")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=all
      WORKING_DIRECTORY "${source}" OUTPUT_VARIABLE _status RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
      message(FATAL_ERROR "Cannot determine Core source changes")
    endif()
    set(_dirty OFF)
    if(NOT _status STREQUAL "")
      set(_dirty ON)
    endif()
  else()
    set(_revision "${OPENMS_SOURCE_REVISION}")
    if(NOT DEFINED OPENMS_SOURCE_DIRTY OR "${OPENMS_SOURCE_DIRTY}" STREQUAL "")
      message(FATAL_ERROR "Source archives require an explicit OPENMS_SOURCE_DIRTY=ON/OFF assertion")
    endif()
    string(TOUPPER "${OPENMS_SOURCE_DIRTY}" _dirty)
    if(NOT _dirty MATCHES "^(ON|OFF|TRUE|FALSE|0|1)$")
      message(FATAL_ERROR "OPENMS_SOURCE_DIRTY must explicitly be ON or OFF")
    endif()
    if(_dirty)
      set(_dirty ON)
    else()
      set(_dirty OFF)
    endif()
  endif()
  string(LENGTH "${_revision}" _length)
  if(NOT _length EQUAL 40 OR NOT _revision MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "OPENMS_SOURCE_REVISION must be the full 40-character lowercase source commit")
  endif()
  if(OPENMS_REQUIRE_CLEAN_SOURCE AND _dirty)
    message(FATAL_ERROR "OPENMS_REQUIRE_CLEAN_SOURCE rejects source changes (including non-ignored untracked files)")
  endif()
  set(${revision} "${_revision}" PARENT_SCOPE)
  set(${dirty} "${_dirty}" PARENT_SCOPE)
endfunction()

# Invoked before compilation: prevent a clean label surviving later edits/commits.
if(DEFINED OPENMS_CHECK_SOURCE_DIR)
  openms_source_identity("${OPENMS_CHECK_SOURCE_DIR}" _current_revision _current_dirty)
  if(NOT _current_revision STREQUAL OPENMS_EXPECTED_REVISION OR
     NOT "${_current_dirty}" STREQUAL "${OPENMS_EXPECTED_DIRTY}")
    message(FATAL_ERROR "Core source identity changed after configuration; rerun CMake before building")
  endif()
endif()
