# SPDX-License-Identifier: BSD-3-Clause
# Compile-only checks respect the actual compiler flags and also work when cross-compiling.
include(CheckCXXSourceCompiles)
function(openms_runtime_abi)
  set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
  foreach(_pair IN ITEMS "LIBCXX;_LIBCPP_VERSION" "LIBSTDCXX;__GLIBCXX__" "MSVC;_MSVC_STL_VERSION")
    list(GET _pair 0 _name)
    list(GET _pair 1 _macro)
    unset(OPENMS_STDLIB_${_name} CACHE)
    check_cxx_source_compiles("#include <string>\n#ifndef ${_macro}\n#error Different standard library\n#endif\nint main() { return 0; }" OPENMS_STDLIB_${_name})
  endforeach()
  set(_cxx11_abi null)
  set(_msvc_runtime null)
  if(OPENMS_STDLIB_LIBCXX)
    set(_library "libc++")
  elseif(OPENMS_STDLIB_LIBSTDCXX)
    set(_library "libstdc++")
    unset(OPENMS_LIBSTDCXX_CXX11_ABI CACHE)
    check_cxx_source_compiles("#include <string>\n#if !defined(_GLIBCXX_USE_CXX11_ABI) || !_GLIBCXX_USE_CXX11_ABI\n#error Old string ABI\n#endif\nint main() { return 0; }" OPENMS_LIBSTDCXX_CXX11_ABI)
    if(OPENMS_LIBSTDCXX_CXX11_ABI)
      set(_cxx11_abi 1)
    else()
      set(_cxx11_abi 0)
    endif()
  elseif(OPENMS_STDLIB_MSVC)
    set(_library "msvc-stl")
    if(CMAKE_MSVC_RUNTIME_LIBRARY)
      set(_msvc_runtime "${CMAKE_MSVC_RUNTIME_LIBRARY}")
    else()
      set(_msvc_runtime "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
    endif()
  else()
    message(FATAL_ERROR "Cannot identify the C++ standard library used to build Core")
  endif()
  set(OPENMS_STANDARD_LIBRARY "${_library}" PARENT_SCOPE)
  set(OPENMS_LIBSTDCXX_CXX11_ABI "${_cxx11_abi}" PARENT_SCOPE)
  set(OPENMS_MSVC_RUNTIME_LIBRARY "${_msvc_runtime}" PARENT_SCOPE)
endfunction()
openms_runtime_abi()
